import React from 'react';
import { useLocation, useParams } from 'react-router-dom';
import Header from '../Header/Header';

const IndustryPage = () => {
  const params = useParams();
  const industry = params.name;
  let title = '',
    primaryContent = '',
    secondaryContent = '';

  if (industry === 'energy') {
    title = 'Energy, Resources and Utilities';
    primaryContent =
      'As demand for petroleum and petroleum products plummeted, oil and gas companies are on the verge of reinventing into socially responsible, sustainable, renewable energy companies. As they expand their portfolio into clean energy space, and commit to net-zero carbon footprint, investors and shareholders have put immense pressure on these companies to provide transparency in achieving net-zero carbon goal over a 10 to 20 year time horizon. This need has caused several oil majors to aggregate thruput and financial performance across generation, trading, customers classification. Zeus Solutions helps oil and gas clients bring disparate data residing across several ERPs, Production, Trading and Manufacturing systems into a single consolidated reportable environment to instill confidence and transparency in investors and stockholders.';
    secondaryContent =
      'Zeus Solutions help Commodities Trading firms with implementation of Trading and Risk Management systems to manage all processes of daily life of a deal and support deliver key critical daily operational reports and KPIs including financial Risk Management metrics leading up to reconciliation of Trade Books to financials. To facilitate cross-commodity exposure and P&L reporting, Zeus is helping Trading clients build a modern digital platform that liberates financial analysts and data scientists from being IT dependent to exploiting unlimited potential of cloud capacity to perform trading forensics, generate trading insights and find market opportunities and risks.';
  }
  if (industry === 'healthcare') {
    title = 'Healthcare and Biotechnology';
    primaryContent =
      'Research and development in biotech and healthcare have increased the dependency on extensive of use of big data that is generated by various research and instrumentation tools, and data available from public and private sources. Effective integration of this data to help develop machine learning techniques and artificial intelligence allow companies predict patterns and create meaniful insights. Companies leverage cloud platforms to scale exponentially to generate insights from global resources that would otherwise take decades to produce outcomes with the complex genetic patterns.';
    secondaryContent =
      'Whether it be human genome or plant genome, Zeus Solutions team helps data scientists develop solutions leading drug discovery, drug recycling, drug safety, functional and structural genomics, proteomics, pharmacogenetics, and pharmacogenomics, among others. Our consultants help accelerate R&D and decision making by aggregating large volumes of test data into consumable information. Data mining from test results are used to identify drug targets, drug adherence, understanding disease mechanisms, process optimization etc.';
  }
  if (industry === 'finance') {
    title = 'Finance and Wealth Management';
    primaryContent =
      'Data is growing at an exponential rate, whether fostered by social media or by devices with built-in chips, big data has become the crux to data-driven insights, decision-making and value generation for many businesses. Companies have witnessed value creation unlike anytime before and compete to make continous advancements to differentiate from their competitions. Companies leveraging the power of cloud to harness exponential scale and unlimited processing capacity, successfully emerge, reinvent and soar in value creation.';
    secondaryContent =
      'Whether it be modernization of current infrastructure, migrating to new cloud platforms, or developing a data foundation, Zeus Solutions helps clients thrive in their digital platform strategy to achieve their goals faster.';
  }
  if (industry === 'telecom') {
    title = 'Telecom Industry';
    primaryContent =
      'The telecom sector is one of the most disrupted fields in modern digitalization and is struggling to keep up with the growing demands of data across every connected device, IoT, video streaming, private and social data among others. Despite the rapid growth in 5G networks and satellite technologies, the need for automation, machine learning and artificial intelligence to increase efficiency and predict consumer behaviors is putting added pressure on Telecom companies. Communication and transmission of information across the networks, data centers and cloud platforms is crucial, more than ever before, all done safely, securely and within the confines of social, government and regulatory framework. Companies are expected to deliver affordable, cost-effective, low maintenance end-use solutions in an extensively competitive global environment.';
    secondaryContent =
      'Zeus Solutions team offers its clients with competency and technical capabilities to deliver a world-class solution, develop insights, boast obvious business value quickly by leveraging blockchain technology, integrating information, streamline business processes and protect personal data and competitively sensitive business data.';
  }
  if (industry === 'agriculture') {
    title = 'Agriculture Industry';
    primaryContent =
      'By 2050, world is expecting to have around 10 Billion people, and India as the fastest developing country is likely to have a population of 1.9 Billion people or more. In order to cater such a population, it’s highly important to put our acts together and focus on enhancing our Agricultural crop quality and yield through innovative Agricultural Technologies, process optimisation and proven package of practices. We at Zeus Solutions, we host Consultancy and Solutions Implementation Services catering to Precision Agriculture Farming through smart irrigation technologies, setting up ERP and CRM customised solutions for supporting Agriculture Enterprise data and Customers, Drone-Aerial Mapping Technologies, Crop enhancement Data Planning, Agri e-Commerce for Customers and optimising Supply Chain Management for D2C and B2B.';
    secondaryContent =
      'Did you know, we can reduce Crop losses and increase yield by implementing Smart AI enabled Agri Technologies? Our team consisting of Agri Consultants and Technologists work closely with our strategic partner who power us to provide AI enabled AgriTech solutions for our clients. We use a combination of Field Sensors and Satellite imaging services to provide near to real time crop status insights which will further help to monitor and take corrective actions to keep your crop healthy and productive.';
  }
  if (industry === 'insurance') {
    title = 'Insurance Industry';
    primaryContent =
      'While we are all being prepared to face risks which we are unaware or aren’t prepared for, we feel happy there are Insurance companies who are spreading the awareness about the need of Insurance and its benefits to individuals. We at Zeus are providing Consulting and Technology services catering to this higher demand of Customer success journeys. Whether it could be family individuals seeking insurance for themselves, their parents or toddlers, its our utmost priority to provide Insurance Consultants who can assist with customised solutions for your Business. Insurance Companies are all spear heading towards Digital transformation, re-designing their servicing capabilities, and providing customer-centric solutions. At Zeus, we feel privileged to partner with companies offering Life, Health, Motor, Property, Medical Insurance products, since we power our InsureTech growth through automation, self service capabilities, ML driven Underwriting processes, and much more…. Suite of services which we offer are fuelled with collaboration, trust, growth, innovation, and partnership.';
    secondaryContent = '';
  }

  return (
    <section className="section-industry-page">
      <div className="full-img img-Industrie-Page">
        <Header />
        <section class="section-contact-us">
          <div class="container">
            <h1 className="heading-primary contact-primary">Industries</h1>
            {/* <h2 className="heading-secondary contact-secondary case">
              Shaping the future
            </h2> */}
          </div>
        </section>
      </div>
      <div class="container about-div">
        <div class="about-div-1">
          <h2 class="heading-secondary">{title}</h2>
          {/* <h3 class="heading-tertiary tertiary-industry-page">
            Equal Opportunity Employment
          </h3> */}
          <p class="feature-text tertiary-industry-page">{primaryContent}</p>
          <br></br>
          <br></br>
          <p class="feature-text tertiary-industry-page">{secondaryContent}</p>
          <br></br>
          <br></br>
          {/* <a href="#cta" class="btn btn--full margin-right-sm btn-rights">
            View All Roles
          </a> */}
        </div>
      </div>
    </section>
  );
};

export default IndustryPage;
